apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: poller
message: 'A poller project'
metadata:
  annotations:
    openshift.io/display-name: "Poller"
    description: >-
      A poller application.
    iconClass: "icon-go-gopher"
    openshift.io/provider-display-name: "Red Hat, Inc." 
  name: poller-template
  namespace: openshift
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: golang
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: golang:1.11
      from:
        kind: DockerImage
        name: golang:1.11
      generation: 1
      importPolicy: {}
      name: "1.11"
      referencePolicy:
        type: Source
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: docker-registry.default.svc:5000/${APP_NAME}
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${APP_REPO}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: golang:1.11
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - imageChange:
      type: ImageChange
- apiVersion: v1
  data:
    default.json: |
      {
        "poll1": {
          "pollDescription": "What number do you think is the best?",
          "options": {
            "1-four": "Four is two plus two",
            "2-five": "Five is the number of fingers",
            "3-six": "Six is six"
          }
        },
        "poll2": {
          "pollDescription": "Another silly poll, choose another number",
          "options": {
            "1-seven": "Seven is the number of the deadly sin",
            "2-eigth": "Eight is four plus four",
            "3-nine": "Nine is three times three"
          }
        }
      }
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: polls
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: ${APP_NAME}-results
    name: ${APP_NAME}-results
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${APP_NAME}-results
      deploymentconfig: ${APP_NAME}-results
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}-results
          deploymentconfig: ${APP_NAME}-results
      spec:
        containers:
        - env:
          - name: typology
            value: results
          image: docker-registry.default.svc:5000/${APP_NAMESPACE}/${APP_NAME}:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9090
            timeoutSeconds: 1
          name: ${APP_NAME}
          ports:
          - containerPort: 9090
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9090
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /go/src/github.com/ugol/poller/polls
            name: polls-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 5
        volumes:
        - configMap:
            defaultMode: 420
            name: polls
          name: polls-volume
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - env:
          - name: typology
            value: ${APP_NAME}
          image: docker-registry.default.svc:5000/${APP_NAMESPACE}/${APP_NAME}:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9090
            timeoutSeconds: 1
          name: ${APP_NAME}
          ports:
          - containerPort: 9090
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9090
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /go/src/github.com/ugol/poller/polls
            name: polls-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 5
        volumes:
        - configMap:
            defaultMode: 420
            name: polls
          name: polls-volume
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 9090-tcp
      port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}-results
    name: ${APP_NAME}-results
  spec:
    ports:
    - name: 9090-tcp
      port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      app: ${APP_NAME}-results
      deploymentconfig: ${APP_NAME}-results
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}-polls
  spec:
    host: ${APP_NAME}.${APP_DOMAIN}
    path: /polls/
    port:
      targetPort: 9090-tcp
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}-results
    name: ${APP_NAME}-results-static
  spec:
    host: ${APP_NAME}.${APP_DOMAIN}
    path: /static/
    port:
      targetPort: 9090-tcp
    to:
      kind: Service
      name: ${APP_NAME}-results
      weight: 100
    wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}-results
    name: ${APP_NAME}-results
  spec:
    host: ${APP_NAME}.${APP_DOMAIN}
    path: /results/
    port:
      targetPort: 9090-tcp
    to:
      kind: Service
      name: ${APP_NAME}-results
      weight: 100
    wildcardPolicy: None
parameters:
  - name: APP_NAME
    displayName: App Name
    description: The Name of the App
    value: poller
    required: true 
  - name: APP_DOMAIN
    displayName: App Domain
    description: The Domain of the App
    value: apps.example.com
    required: true
  - name: APP_REPO
    displayName: App Repo
    description: The Repo of the APp
    value: https://github.com/ugol/poller.git
    required: true
